### ISSUE TITLE
`getSession()` does not listen to the SessionProvider baseUrl

### ISSUE THREAD

**Issue by rcannood** [solidjs-community/mediakit#146]
Hi @OrJDev ! Thanks for creating a solidstart authjs package!

I'm running into an issue, where passing a baseUrl to the SessionProvider doesn't seem to affect a part of the code.

----

In my `app.tsx`, I'm passing a baseUrl to the SessionProvider:

```jsx
              <SessionProvider baseUrl={getServerBaseUrl()}>
                <Layout>{props.children}</Layout>
              </SessionProvider>
```

However, when trying to authenticate on Deno Deploy, I get:

    @auth TypeError: error sending request for url (http://localhost:3000/api/auth/session): client error (Connect): tcp connect error: Cannot assign requested address (os error 99): Cannot assign requested address (os error 99)
        at async mainFetch (ext:deno_fetch/26_fetch.js:177:12)
        at async fetch (ext:deno_fetch/26_fetch.js:423:7)
        at async A$b (file:///src/server/index.ts:34473:13)
        at async n (file:///src/server/index.ts:34454:17)
        at async s (file:///src/server/index.ts:34459:23)
        at async file:///src/server/index.ts:34461:77

-----

I have a feeling that this is because the following code does not listen to the sessionprovider's baseUrl:

https://github.com/solidjs-community/mediakit/blob/9f1054bb1027b85ec6ead8b0403c754eb80d4c5a/packages/auth/solid/src/client.tsx#L238

Because `getUrl` only looks at `AUTH_URL_INTERNAL`, `AUTH_URL`, `VERCEL_URL`, all of which are undefined in my case.

**Comment by rcannood** [comment]
Hi @OrJDev ! 

Any updates on this? Is there a way to get the implementation of `getUrl` to look at the `baseUrl` which I can pass to the SessionProvider?

Much appreciated!
Robrecht

**Comment by rcannood** [comment]
But what is the use of the baseUrl in the SessionProvider if not for this reason?

In my use case I can't set the AUTH_URL because it needs to be set dynamically depending on the infrastructure it is deployed to, and I don't have the capability of injecting an AUTH_URL environment variable.
