### ISSUE TITLE
`pRPC` crash

### ISSUE THREAD

**Issue by hngngn** [solidjs-community/mediakit#52]
### Current behavior

Following [this](https://mediakit-taupe.vercel.app/prpc/query) and get instant crash, here is the error log:

```bash
TypeError: /home/projects/github-a9ukgq-1qvmle/src/routes/index.tsx: Cannot read properties of undefined (reading 'value')
    at j (file:///home/projects/github-a9ukgq-1qvmle/node_modules/@solid-mediakit/prpc-plugin/dist/esm/production/index.mjs:18:1941)
    at PluginPass.CallExpression (file:///home/projects/github-a9ukgq-1qvmle/node_modules/@solid-mediakit/prpc-plugin/dist/esm/production/index.mjs:18:5272)
    at newFn (file:///home/projects/github-a9ukgq-1qvmle/node_modules/@babel/traverse/lib/visitors.js:160:14)
    at NodePath._call (file:///home/projects/github-a9ukgq-1qvmle/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (file:///home/projects/github-a9ukgq-1qvmle/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (file:///home/projects/github-a9ukgq-1qvmle/node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (file:///home/projects/github-a9ukgq-1qvmle/node_modules/@babel/traverse/lib/context.js:89:16)
    at TraversalContext.visitSingle (file:///home/projects/github-a9ukgq-1qvmle/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (file:///home/projects/github-a9ukgq-1qvmle/node_modules/@babel/traverse/lib/context.js:112:19)
    at traverseNode (file:///home/projects/github-a9ukgq-1qvmle/node_modules/@babel/traverse/lib/traverse-node.js:22:17) {
  code: 'BABEL_TRANSFORM_ERROR',
  plugin: 'prpc',
  id: '/home/projects/github-a9ukgq-1qvmle/src/routes/index.tsx?pick=default&pick=$css',
  pluginCode: "import { query$ } from '@solid-mediakit/prpc';\n" +
    "import { z } from 'zod';\n" +
    'const Home = () => {\n' +
    '  const testQuery = query$({\n' +
    '    queryFn: async ({\n' +
    '      payload,\n' +
    '      event$\n' +
    '    }) => {\n' +
    "      const ua = event$.request.headers.get('user-agent');\n" +
    '      console.log({\n' +
    '        ua\n' +
    '      });\n' +
    '      return `hey ${payload.hello}`;\n' +
    '    },\n' +
    "    key: 'hello',\n" +
    '    schema: z.object({\n' +
    '      hello: z.string()\n' +
    '    })\n' +
    '  });\n' +
    '  const hello = testQuery(() => ({\n' +
    "    hello: 'JDev'\n" +
    '  }));\n' +
    '  return <div>{hello.data}</div>;\n' +
    '};\n' +
    'export default Home;'
}
```

### Reproduce
[Here](https://stackblitz.com/edit/github-a9ukgq-1qvmle?file=src%2Froutes%2Findex.tsx)

**Comment by OrJDev** [comment]
it doesn't seem like it crashes can you check that please, will fix this now.

**Comment by hngngn** [comment]
> it doesn't seem like it crashes can you check that please, will fix this now.

Here's the code where the issue arises:

```tsx
import { query$ } from '@solid-mediakit/prpc';
import { z } from 'zod';

export const testQuery = query$({
  queryFn: async ({ payload, event$ }) => {
    const ua = event$.request.headers.get('user-agent');
    console.log({ ua });
    return `hey ${payload.hello}`;
  },
  key: 'hello',
  schema: z.object({
    hello: z.string(),
  }),
});
```

This make the app crashes after a few seconds. However, using `builder$` resolves the issue:

```tsx
const testBuilder = builder$();

export const testQuery = testBuilder
  .input(
    z.object({
      hello: z.string(),
    })
  )
  .query$(({ payload }) => {
    return `Hello ${payload.hello}`;
  }, 'test-query');
```

from my understanding i thought `query$` could be used independently, similar to this:
```tsx
const query = createQuery(() => ({
    queryKey: ['todos'],
    queryFn: fetchTodos,
  }))
```

but i might be missing something

**Comment by OrJDev** [comment]
ahh yes i see the issue, this is related to one of my recent commits trying to fix pipe$, seems like i broke how we get the middlewares. basically the plugin thought you had middleware even tho you don't so it tried to access its name, fixed in 

https://github.com/solidjs-community/mediakit/commit/604d2740655a6d9450d6459214e7fb368d292c19


please try and lmk if its fixed.

**Comment by hngngn** [comment]
the new version fixed the issue, so I played around a bit more and found another bug?

```tsx
import { builder$, query$ } from '@solid-mediakit/prpc';
import { z } from 'zod';

export const testQuery = query$({
  key: 'test-query',
  queryFn: ({}) => {
    return 'test-query';
  },
});

const mainBuilder = builder$();

export const testQueryWithBuilder = mainBuilder
  .input()
  .query$(({}) => {
    return 'test-query';
  }, 'test-query-with-builder');
```

both `queryFn` and the `query$` need `{}` to not crash, but with the builder is also need an `input`

maybe no one will using like this, but it crash the app too, so I'll put it here anyway:

```tsx
queryFn: ({}) => 'test-query'
```

```tsx
queryFn: () => 'test-query'
```

```tsx
query$(({}) => 'test-query', 'test-query-with-builder')
```

```tsx
query$(() => 'test-query', 'test-query-with-builder')
```

**Comment by OrJDev** [comment]
I saw this issue, i need to clear out my time to get it fixed as lately ive been getting home late

**Comment by OrJDev** [comment]
fixed in https://github.com/solidjs-community/mediakit/commit/b23ff80d6d32508b4cf51fc5ae869dd4454ff5fb
please try and lmk if it works as expected. if not, reopen this issue

**Comment by OrJDev** [comment]
https://github.com/solidjs-community/mediakit/releases/tag/%40solid-mediakit%2Fprpc-plugin%401.3.1
