### ISSUE TITLE
Does not support Auth0

### ISSUE THREAD

**Issue by joeygrable94** [solidjs-community/mediakit#58]
This library does not support an Auth0/Okta configuration.

**Comment by OrJDev** [comment]
I remember someone was able to set up auth0, see here

https://github.com/solidjs-community/mediakit/issues/46

Anyways this library is just a SolidStart wrapper for AuthJS, we don't add any features (besides utilities designed for Solid), if you want to ask for a feature or a report an issue within the core of authjs, check out this repo

https://github.com/nextauthjs/next-auth

**Comment by OrJDev** [comment]
Can you try that and lmk if its working as expected:

https://authjs.dev/getting-started/providers/auth0#configuration

**Comment by joeygrable94** [comment]
The #46 example provided lacks context nor code.

**Comment by joeygrable94** [comment]
[auth][error] InvalidProvider: Callback route called without provider. Read more at https://errors.authjs.dev#invalidprovider
    at Module.callback (file:///Users/joeyg/Sites/solid-auth/node_modules/@auth/core/lib/actions/callback/index.js:11:15)
    at AuthInternal (file:///Users/joeyg/Sites/solid-auth/node_modules/@auth/core/lib/index.js:27:38)
    at async Module.Auth (file:///Users/joeyg/Sites/solid-auth/node_modules/@auth/core/index.js:109:34)
    at async eval (/Users/joeyg/Sites/solid-auth/node_modules/@solidjs/start/dist/server/handler.js:30:23)
    at async _callHandler (file:///Users/joeyg/Sites/solid-auth/node_modules/h3/dist/index.mjs:1821:16)
    at async _callHandler (file:///Users/joeyg/Sites/solid-auth/node_modules/h3/dist/index.mjs:1821:16)
    at async file:///Users/joeyg/Sites/solid-auth/node_modules/h3/dist/index.mjs:1962:19
    at async Object.callAsync (file:///Users/joeyg/Sites/solid-auth/node_modules/unctx/dist/index.mjs:72:16)
    at async Server.toNodeHandle (file:///Users/joeyg/Sites/solid-auth/node_modules/h3/dist/index.mjs:2249:7)
