### ISSUE TITLE
Auth: UnknownAction: Cannot parse action at /api/auth/session

### ISSUE THREAD

**Issue by oglassdev** [solidjs-community/mediakit#85]
When I use a server function when navigating using solid router (not loading directly from the path), I get this error. Provided is the stack trace and the function. Currently, for testing, I am simply returning the session instead of fetching the actual data.

```ts
export const getPlayers = cache(async () => {
  "use server";
  let request = getWebRequest();
  let session = await getSession(request, authOptions);
  
  return session == null ? "invalid" : JSON.stringify(session);
}, "players");
```

```
[auth][error] UnknownAction: Cannot parse action at /api/auth/session. Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (file:///Users/<user>/development/<project>/node_modules/@auth/core/lib/utils/web.js:92:15)
    at toInternalRequest (file:///Users/<user>/development/<project>/node_modules/@auth/core/lib/utils/web.js:24:40)
    at Module.Auth (file:///Users/<user>/development/<project>/node_modules/@auth/core/index.js:67:35)
    at Module.getSession (/Users/<user>/development/<project>/node_modules/@solid-mediakit/auth/index.js:210:48)
    at $$function0 (/Users/<user>/development/<project>/src/server/db.ts:42:45)
    at eval (/Users/<user>/development/<project>/node_modules/@solidjs/start/dist/runtime/server-handler.js:109:14)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Module.provideRequestEvent (file:///Users/<user>/development/<project>/node_modules/solid-js/web/storage/dist/storage.js:7:14)
    at handleServerFunction (/Users/<user>/development/<project>/node_modules/@solidjs/start/dist/runtime/server-handler.js:102:46)
    at async _callHandler (file:///Users/<user>/development/<project>/node_modules/h3/dist/index.mjs:1821:16)
    at async file:///Users/<user>/development/<project>/node_modules/h3/dist/index.mjs:1962:19
    at async Object.callAsync (file:///Users/<user>/development/<project>/node_modules/unctx/dist/index.mjs:72:16)
    at async Server.toNodeHandle (file:///Users/<user>/development/<project>/node_modules/h3/dist/index.mjs:2249:7)
```

**Comment by oglassdev** [comment]
I've confirmed it still happens when using
```ts
  let request = getRequestEvent()!;
  let session = await getSession(request.request, authOptions);
```

**Comment by OrJDev** [comment]
```tsx
import { getSession } from '@solid-mediakit/auth'
import { cache, createAsync } from '@solidjs/router'
import { type VoidComponent } from 'solid-js'
import { getWebRequest } from 'vinxi/server'
import { authOptions } from '~/server/auth'

const getPlayers = cache(async function () {
  'use server'
  let request = getWebRequest()
  let session = await getSession(request, authOptions)

  return session == null ? 'invalid' : JSON.stringify(session)
}, 'test')

const Home: VoidComponent = () => {
  const user = createAsync(() => getPlayers())

  return (
    <main class='flex flex-col items-center justify-center gap-4'>
      <span class='text-xl text-black'>Welcome to Solid Auth</span>
      <pre>{user()}</pre>
    </main>
  )
}

export default Home

```

that seems to work fine for me, can you please update all your deps and try?
<img width="1440" alt="Screenshot 2024-07-24 at 22 19 50" src="https://github.com/user-attachments/assets/24585440-4994-40de-8e61-fbc55614f064">

**Comment by OrJDev** [comment]
after some more debugging i faced this issue, it is now solved

https://github.com/solidjs-community/mediakit/commit/80e725465080310ce60d1013dece47b647ac239b

thank you for letting me know.

**Comment by OrJDev** [comment]
please reopen if you continue facing this issue.
